commands/BitcoinPriceCommand.js
commands/CatFact.js

A-Asking mastew ^w^ t-to accept me

---

commands/GoogleAi.js
package-lock.json
package.json

Anyways here's a nice pic of silverwolf when you show her gamebang fics :

mastew bwanch~san, i added ai tuwu ouw pwoject pwease give me headpats

---

commands/GoogleAi.js
commands/claim.js

maybe some of yall need it 
anyways

Cornflakes were invented to suppress sexual desires 

---

commands/claim.js

Controllers can be nasty, whether you're 12,000ft underwater or 65,000ft in virtual skies, a stick drift can ruin your day. Wireless or wired? Both have their advantages and they're often argued a lot about which is better.
But in this case.....stick drift won't be an issue!! Nor will you complain about the disadvantages of wired controllers!

Don't think, just claim. 95% of users break their streak before they hit the golden nuggie.

---

classes/silverwolf.js
commands/classes/admincommand.js
commands/dm.js
commands/say.js

Fuck Ai for being so censored and boring, but what if you wanted good ol' silverwolf to dm you instead without allat?
lowkey useless apart from trolling.
However! I propose an announcement broadcast feature! (works only if they share server mutuals)

Silverwolf slides into your dms

---

commands/Timestamp.js
commands/classes/devcommand.js

oops it seems the egghunt when here aswell
anyways silverwolf 
Just so you know, I have no idea if /discord_timestamp works well...I'm too lazy to test it fully.

Are you the dumbest coder cuz you use GPT or you use GPT cuz you are the dumbest coder

---

commands/Timestamp.js

:/
silverwolf so that guy named mewtwo2387 can merge https://www.pixiv.net/en/artworks/116432272

flipped the fucking minus sign

---

commands/add.js
commands/balance.js
commands/buy.js
commands/buybitcoin.js
commands/claim.js
commands/eat.js
commands/nuggieboard.js
commands/slots.js
commands/upgrade.js
utils/math.js

either that or nerf slots ![image](https://github.com/user-attachments/assets/3c3c5b5c-3a96-49be-9857-c16ec8d6c5e5)

added thousand separators and formatting cause electro and fit exist

---

commands/avartar.js
commands/pfpmatch.js

Okay now you can steal it now duh
Okay in this merge there is also the pfp match that...kinda works ? Doesn't matter fuck this. We ball. Nobody's gonna use it anyways. It's useless.

Ever saw an amazing Silverwolf pfp and said. "I want that."

---

commands/fart.js
commands/rnr.js
commands/russianRoulette.js
commands/sing.js
data/songs.json

RIsk n Reward is the only functional one here
anyways take a silverwolf i promise I'll finish the others.

buncha unfinished stuff but who cares

---

classes/database.js
classes/silverwolf.js
commands/buy.js
commands/upgrade.js
commands/upgradedata.js
tests/slots.js
utils/upgrades.js

and member summoning too but i kinda forgot about that

fuck you, no more instant cook

---

classes/birthdayScheduler.js
classes/database.js
classes/silverwolf.js
commands/birthdayGet.js
commands/birthdaySet.js
package-lock.json
package.json

idk 
it works 
if it doesnt idk
maybe it works
maybe it doesn't
meh
but who cares rite ? rite ?

if it works it works

---

classes/silverwolf.js
data/status.json
tests/slots.js

playing statuses 

---

commands/grabEmoji.js
commands/say.js
data/status.json

anti nitro project 💅 

---

commands/fakequote.js
commands/say.js

White representation and b&w pfp options
genshin could never amirite ? 
ahem

Diversity update

---

classes/silverwolf.js
commands/8ball.js
commands/8ball2.js
commands/avartar.js
commands/execute.js

I hope it works man 
despair 
anyways heres silverwolf

I called pest control 

---

classes/database.js
commands/ascend.js
commands/ascensionupgrade.js
commands/balance.js
commands/buy.js
commands/buyascension.js
commands/claim.js
commands/eval.js
commands/upgrade.js
utils/ascensionupgrades.js
utils/upgrades.js

artifically inflating playtime with ascension

---

commands/blame.js
commands/classes/command.js

So that the bot doesnt crash when someone inputs something funny

Global Error handling

---

commands/8ball.js
commands/8ball2.js
commands/claim.js

spaghetti code 1.0 -> spaghetti code 2.0

Corrected claim 💢 

---

classes/birthdayScheduler.js
commands/birthdaySchedulerTest.js
commands/broadcast.js

fuck this bs
do first
fix later

yolo merge into master

---

commands/guide.js

added a guide for the smooth brains

---

classes/silverwolf.js
commands/forceSummon.js

It's xe_iris!
30% chance of not showing username
3% chance of shiny

Guess the pokemon! (and shinies)

---

classes/database.js
commands/awdangit.js
commands/setserverrole.js

1% to become a girl 99% to earn 1M
and server specific roles

aw dang it!

---

classes/silverwolf.js
commands/silverwolfAI.js
package-lock.json
package.json

the real silverwolf ai on c.ai

---

.gitignore
classes/database.js
classes/silverwolf.js
commands/blackjack.js
commands/gamblerboard.js
commands/profile.js
commands/roulette.js
commands/slots.js

all your gambling statistics will be recorded
gambler's leaderboard 🔥

Competitive Gambling just dropped!!! 🔥 (and profiles)

---

commands/arlecchino.js
commands/blackjack.js
commands/claim.js
commands/fakequote.js
commands/genshinProfile.js
commands/marriageDivorce.js
commands/profile.js
commands/roulette.js
commands/slots.js
data/arlecchino.json
data/genshinNamecards.json
data/genshinPfps.json
utils/divorceSettlement.js
utils/marriageBenefits.js

I took a nice shit recently

---

classes/database.js
commands/ascensionupgrade.js
commands/buyascension.js
commands/claim.js
commands/profile.js
utils/ascensionupgrades.js
utils/upgrades.js

new ascension upgrade: nuggie multi based on credits
max level is now 100

Maxing all upgrades no longer removes the motivation from gambling for more credits!!

---

classes/silverwolf.js
commands/claim.js

The spooky update

---

classes/silverwolf.js
commands/claim.js

no sw for you ei, its november.

removed halloween update

---

classes/database.js
commands/blackjack.js
commands/profile.js
commands/roulette.js

+6%/streak for roulette
+8%/streak for blackjack

Roulette and bj streaks :fire:

---

commands/catcg.js

#55 
releases a pokemon
who's gonna be the first to fall for it? i put 10000 nuggies on finch

fake catch command /catcg

---

commands/add.js
commands/balance.js
commands/blackjack.js
commands/roulette.js
commands/slots.js
commands/transfer.js
package-lock.json
package.json
tests/math.test.js
utils/math.js

Shortening big numbers ( #58 ) and inputting big numbers ( #57 )
and yes we have test suites now

Handling bigger numbers for all the gamblers

---

classes/database.js
commands/gongyoo.js
commands/slots.js

ei help me balance this game-
anyways here's sw build guide for no reason

Squid game references :fire:

---

commands/blackjack.js

shortest pr ever
why did i even make one if i am the one merging

Stopping soren from exploiting bj

---

commands/classes/command.js

Sorry, description isn't available right now.
A law banning PR descriptions has been enacted in Silverwolf Corp Ltd. Unfortunately, that means you can't see the description here.
We are fortunate that Iruma has indication he will work with us on a solution to reinstate descriptions once he is unbanned. Please stay tuned!

Iruma propaganda

---

classes/babyScheduler.js
classes/database.js
classes/sexSession.js
classes/silverwolf.js
commands/baby_birth.js
commands/baby_enslave.js
commands/baby_get.js
commands/baby_murder.js
commands/baby_name.js
commands/claim.js
commands/commandgroups/baby.js
commands/commandgroups/sex.js
commands/dbdump.js
commands/mixins/leaderboardMixin.js
commands/murderboard.js
commands/nuggieboard.js
commands/profile.js
commands/sex_start.js
commands/sex_status.js
commands/sex_thrust.js

PR #69 - SEX UPDATE (f.t. slavery)
